### PR TITLE
Added tests directory to package.json

### PR DESCRIPTION
**Pull request by alebsack**
@alazier this will help test the node modules on different node versions and platforms after building.

### CODE REVIEW

**Comment by alazier** [comment]
I just pushed a changed to remove the ios files/app from the package. Think we should do some more cleanup before shipping this but overall I think this is good as long as it doesn't increase the package size. Does anyone else have thoughts on this?

**Comment by alebsack** [comment]
After installing the npm module for node, I'd like to be able to:
```
cd tests
npm install
npm run test-nosync
```

**Comment by alebsack** [comment]
@fealebenpae @radu-tutueanu Do you have any thoughts?

**Comment by radu-tutueanu** [comment]
That sounds good to me. 👍

**Pull request merged**
