### PR TITLE
[React-Native] Android - buildToolsVersion to 25.0.2

### PR DESCRIPTION
**Pull request by ovr**
Hey!

I was trying to change buildToolsVersion inside my project `app/build.graddle`
But every time this require 25 >=

```
* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugApk'.
   > A problem occurred configuring project ':realm'.
      > The SDK Build Tools revision (23.0.1) is too low for project ':realm'. Minimum required is 25.0.0
```

Is it possible to upd buildToolsVersion? Or If you can please give a good advice

Thank 🍻

### CODE REVIEW

**Comment by jaggs6** [comment]
@blagoev please merge this

**Comment by kristiandupont** [comment]
@ovr apologies for the late response. Thank you for contributing this. We would like to merge it -- would you mind signing our [CLA](https://github.com/realm/realm-js/blob/master/CONTRIBUTING.md#cla)? Thank you :-)

**Comment by jaggs6** [comment]
@ovr

**Comment by ovr** [comment]
@jaggs6 Yeap, I am using this hack now
@kristiandupont Accepted CLI

**Comment by blagoev** [comment]
@ovr thanks for your contribution

**Pull request merged**
