### PR TITLE
Extend jest test-runner test

### PR DESCRIPTION
**Pull request by takameyer**
Extended the test runner for jest to prove that opening and
closing a realm will not fail or hang on shut down.

## ☑️ ToDos

* [x] 📝 Changelog entry
* [x] 🚦 Tests

### CODE REVIEW

**Review by kraenhansen — APPROVED** [review]
Seems legitimate 🙂

**Review by kneth — APPROVED** [review]
Good idea to check if `Realm` can be used.

**Comment by takameyer** [comment]
Will rebase when core update is merged.  This will fix the tests.

**Review by fronck — APPROVED** [review]

**Comment by kneth** [comment]
@takameyer I have merged the core upgrade

**Pull request merged**
