### PR TITLE
A schema is required when Realm is opened in a query-based sync situation

### LINKED ISSUE #1976: Query-based sync requires a schema
## Goals

Either fail with an exception or succeed when subscribing.

## Expected Results

When opening a schema-less query-based synced Realm, an exception should be thrown.

## Actual Results

An segmentation fault happens when `subscribe()` is called.

## Steps to Reproduce

See below.

## Code Sample

```
var Realm = require('realm');

// the URL to the Realm Object Server
var SERVER_URL = 'localhost:9080';
let userUuid = 'realm-admin';

Realm.Sync.User.login('http://' + SERVER_URL, userUuid, '').then(user => {
  const config = user.createConfiguration({
      sync: { url: 'realm://' + SERVER_URL + '/my-test-app',
          error: err => console.log(err)
        },
  });
  Realm.open(config).then(realm => {
      let subscription = realm.objects('Test').subscribe(); // segfault!!!
    })
});
```

## Version of Realm and Tooling

- Realm JS SDK Version: 2.14.2
- Node or React Native: node
- Client OS & Version: any
- Which debugger for React Native: None

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

When a Realm is opened for query-based sync, `subscribe()` will fail if no schema is defined.

This closes #1976 and #1977 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 🚦 Tests
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* ~[ ] typescript definitions file is updated~
* [x] jsdoc files updated
* ~[ ] Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

**Comment by kneth** [comment]
@nirinchev True but only if your configuration is generated by `createConfiguration` and you haven't modified the `schema` part.

**Comment by nirinchev** [comment]
But if you modified the schema part, doesn't that mean that 1) you have a schema, and 2) that the default schema should get merged with yours?

**Comment by nirinchev** [comment]
To be clear, I think that while the changes in this PR are fine, but a real fix would be to make sure we add the permission classes always as this will address both this issue and the one reported by Christian.

**Comment by kneth** [comment]
The check here will be replaced by https://github.com/realm/realm-js/issues/1988

**Pull request merged**
