### PR TITLE
Use CreatePolicy (object store)

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes https://jira.mongodb.org/browse/RJS-349

## ☑️ ToDos

* [x] 📝 Changelog entry
* ~[ ] 📝 `Compatibility` label is updated or copied from previous entry~
* ~[ ] 🚦 Tests~
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* ~[ ] typescript definitions file is updated~
* ~[ ] jsdoc files updated~
* ~[ ] Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

**Comment by bmunkholm** [comment]
@blagoev - relevant to N-API updates as well?

**Comment by kneth** [comment]
> relevant to N-API updates as well?

@bmunkholm @blagoev I don't think so as the changes here are above the engine level.

**Comment by blagoev** [comment]
Yeah not relevant for napi

**Comment by kneth** [comment]
Merging. Only integration test (RN iOS) is failing due to missing iPhone simulator.

**Pull request merged**
