### PR TITLE
App crashes on the first launch

### PR DESCRIPTION
**Pull request by max-zu**
## What, How & Why?

This closes [2400](https://github.com/realm/realm-js/issues/2400) ???

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Comment by bmunkholm** [comment]
Great find @max-zu! We need you to accept the CLA (in you haven't already) and add a test and changelog message.
Thanks!

**Comment by kneth** [comment]
@max-zu Thank you for your contribution.

I ran all node.js (on MacOS) and RN test locally, and they are passing.  Can you add a test? And update `CHANGELOG.md`, please?

**Comment by max-zu** [comment]
Could you describe more detailed, what should I do ?)

**Comment by kneth** [comment]
@max-zu I was wondering if you can find a way to test that the exception is thrown. Clearly we don't have such a test as this bug hasn't surfaced before.

**Pull request merged**
