### PR TITLE
Fix security vulnerabilities

### PR DESCRIPTION
**Pull request by kneth**
`npm audit` reports many issues.

### CODE REVIEW

**Comment by fadookie** [comment]
@kneth thanks for fixing these. Do you know when the next release will be that will include these fixes?

**Comment by kneth** [comment]
@fadookie I plan to do a release tomorrow.

**Comment by DVLNarayana** [comment]
@kneth : while downloading realm latest version(2.14.2) through npm in package.json still it showing node-pre-gyp : "^0.6.36" but in the github master version showing node-pre-gyp : "^0.11.0" it  is means latest changes are not publish?

**Comment by kneth** [comment]
@DVLNarayana Due to a glitch on build systems, I wasn't able to release.

**Comment by DVLNarayana** [comment]
when i can expect the release?

**Comment by kneth** [comment]
Once #1975 is merged, I can make a release. I hope to do it tomorrow or Thursday.

**Pull request merged**
