### PR TITLE
Upgrade to Realm Core 11.6.0. Was: Adopting to changes in Realm Core (past 11.4.1)

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

I needed to consume an unreleased version of Realm Core after v11.4.1.
This PR contains the modifications I had to do to adopt to the changes in Realm Core.

Feel free to merge this PR into whatever branch we'll be using when upgrading Realm Core to the version after 11.4.1, once that gets released.

## ☑️ ToDos
* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Review by kneth — APPROVED** [review]

**Comment by kraenhansen** [comment]
I rebased on latest master. I'll merge as soon as we've got a green build.

**Review by fronck — APPROVED** [review]
LGTM :+1:

**Comment by ironage** [comment]
FYI, core v11.5.2 had a regression with streaming download notifiers, you may wish to hold of releasing this until the next core version which will include https://github.com/realm/realm-core/pull/5008

**Comment by tomduncalf** [comment]
Using this for my sync branch and it works 👍

**Review by tomduncalf — APPROVED** [review]

**Pull request merged**
