### PR TITLE
PR feedback fixes from object store pr

### PR DESCRIPTION
**Pull request by alazier**

### CODE REVIEW

**Comment by appden** [comment]
I think it's easier to just wait for that PR to land, and then just merge it into our repo. That way we don't have a bunch of duplicate commits.

**Comment by alazier** [comment]
We won't have duplicate commits - we are using git subtree.

**Comment by alazier** [comment]
@appden anything left to do here or are we good to merge?

**Comment by appden** [comment]
I believe this is good to go!

**Pull request merged**
