### PR TITLE
Nh/fix android job

### LINKED ISSUE #558: Get android working on ci
We need to figure out how to get our android tests running again.

### PR DESCRIPTION
**Pull request by nhachicha**
Fixes #558
!!! DO NOT MERGE YET !!!

### CODE REVIEW

**Comment by nhachicha** [comment]
CI: retest this please

**Comment by nhachicha** [comment]
CI: retest this please

**Comment by nhachicha** [comment]
retest this please

**Comment by alebsack** [comment]
Closed by #666

**Pull request closed without merging**
