### PR TITLE
Use Object.defineProperty rather than Object.defineProperties because it is faster

### PR DESCRIPTION
**Pull request by RedBeard0531**
Yes, this is kinda stupid, but the results are fairly significant. And, IMO at least, the code is as clear or clearer like this.

FYI, I'm looking into how to get our list perf back up to v11 levels (or better), and this was part of that work. Once I discovered the impact of this, I figured I might as well globally replace all of `Object.defineProperties` and bank that improvement, before doing additional List/OrderedCollection-specific optimization. I'll pick those back up tomorrow.

Edit: I decided to sneak a second related commit in once I remembered that the combination of `prop!: Type` and `Object.declareProperty()` was bad news. The first commit made it more obvious that we were doing that.

Before:
```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (81,881 ops/sec, ±22%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (108,726 ops/sec, ±14.99%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (211,068 ops/sec, ±15.59%)
```

After first commit (using `Object.declareProperty`):
```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (90,663 ops/sec, ±29.44%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (117,569 ops/sec, ±24.64%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (255,618 ops/sec, ±24.08%)
```

After second commit (using `declare property`):
```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (142,468 ops/sec, ±42.28%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (185,514 ops/sec, ±28.95%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (316,215 ops/sec, ±27.6%)
```

## What, How & Why?

This closes # ??? 

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [ ] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated

### CODE REVIEW

**Comment by RedBeard0531** [comment]
Converting to draft to fix test failures. Hold off on reviewing for now.

**Review by kneth — APPROVED** [review]
The numbers are clear, and it makes sense to let them show the path.

Interestingly, [`Object.defineProperty()` is reported to be slow](https://bugs.chromium.org/p/v8/issues/detail?id=8447#c12) for V8. It doesn't contradict this PR and it hints that `Object.defineProperties()` is much slower than it should be.

Do we have numbers for Hermes and JSC?

**Comment by RedBeard0531** [comment]
> The numbers are clear, and it makes sense to let them show the path.
> 
> Interestingly, [`Object.defineProperty()` is reported to be slow](https://bugs.chromium.org/p/v8/issues/detail?id=8447#c12) for V8. It doesn't contradict this PR and it hints that `Object.defineProperties()` is much slower than it should be.

I think that bug was before https://v8.dev/blog/faster-class-features. That post was what tipped me off that there might be some new optimizations available for `Object.defineProperties()`, and I decided to check if they weren't all available to `defineProperties()`.

> Do we have numbers for Hermes and JSC?

Not yet. I can get hermes numbers today. Would JSC numbers affect our decision at all?

**Review by kraenhansen — APPROVED** [review]
This is mildly frustrating. Do you have any insights into why its faster to call `Object.defineProperty`? Are you sure this is the case on Hermes & JSC too?

I would love if we could document these findings / assumptions somewhere, so we don't accidentally refactor this in the future and regress the performance gain.

**Comment by RedBeard0531** [comment]
> Converting to draft to fix test failures. Hold off on reviewing for now.

Ok, fixed. The issue was that we were using `this.realm` in the constructor prior to setting the property, and I changed it to just `realm` (the argument). I also changed `this.results` to `results` in the `addListener` callback while I was at it, not because it was necessary (since that expression doesn't evaluate until after init completes), but because A) it is easier to just have the rule be to not use `this.blah` in that ctor, and B) there is no reason to use indirection through `this` there, since both `this` and `results` are eagerly bound in the `=>` lambda, so it couldn't possibly evaluate to anything else.

**Comment by RedBeard0531** [comment]
I was slightly concerned that the issue with `defineProperties` was caused by hitting some perverse case when redefining properties, potentially in a different order, so I tried going back to using `defineProperties`, but with `declare prop`. The results show that both changes make sense, both separately and together (at least on node 18).

```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (116,515 ops/sec, ±34.78%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (158,146 ops/sec, ±22.99%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (260,956 ops/sec, ±22.42%)
```

The best results are still with `Object.defineProperty` + `declare prop`. I'll try testing with hermes soon.

**Comment by RedBeard0531** [comment]
Ok, after much struggle, I now have the hermes numbers, and they are quite _interesting_, but don't suggest any changes to this PR.

Summary:
* Hermes doesn't seem to care much about `declare prop` vs `prop!`. Perf difference on that axis is within the run-to-run noise range. It is possible that it literally makes *no* difference since something in the metro/hermes chain just completely ignores it (my unconfirmed theory)
* Hermes might slightly prefer `declareProperty` for normal properties, but the difference is small and it is hard to be sure it isn't noise.
* Hermes *really* hates `declareProperties` for `Symbol` properties. They are used by Dictionary, and I think that is why there is a huge improvement in this PR for the `bool?{}` case.

`prop!` + `defineProperties` (baseline):
```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (39,783 ops/sec, ±18.25%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (45,996 ops/sec, ±16.59%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (51,490 ops/sec, ±16.03%)
```


`prop!` + `defineProperty` (patch 1):
```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (41,343 ops/sec, ±16.7%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (48,760 ops/sec, ±16.66%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (82,426 ops/sec, ±19.77%)
```

`declare prop` + `defineProperties`:
```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (40,020 ops/sec, ±14.8%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (47,643 ops/sec, ±14.1%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (53,016 ops/sec, ±15.75%)
```

`declare prop` + `defineProperty` (full PR):
```
    reading property of type 'bool?[]'
      ✓ reads bool?[] (41,139 ops/sec, ±20.84%)
    reading property of type 'bool?<>'
      ✓ reads bool?<> (48,287 ops/sec, ±17.62%)
    reading property of type 'bool?{}'
      ✓ reads bool?{} (82,485 ops/sec, ±22.28%)
```


I would really rather not collect all of these numbers for JSC. It would take a long time, and I suspect that we wouldn't change any decisions based on them.

**Pull request merged**
