### PR TITLE
[iOS] Support RN 0.46+, #1121

### PR DESCRIPTION
**Pull request by ovr**
Hey!

Issue: #1121
Small PR that helps us to support RN 0.46+

Thank

### CODE REVIEW

**Comment by ovr** [comment]
Should I wrap code by `@try` and log exception? Thank

**Comment by compojoom** [comment]
Tested the fix and it works for me.

**Comment by fealebenpae** [comment]
Thanks @ovr!

**Comment by Ingibjorg** [comment]
@fealebenpae can you tell me when you'll release this? I tried referencing your commit in my packager but then I get a build error when I run my project with Xcode. 
```
clang: error: no such file or directory: '/Users/me/my_project/node_modules/realm/vendor/GCDWebServer/GCDWebServer/Core/GCDWebServerRequest.m'
clang: error: no input files
```

**Pull request merged**
