### PR TITLE
Fix ( Fatal Issue TypeError: Cannot read property '_objectKey' of undefined #6925 )

### PR DESCRIPTION
**Pull request by Ashik55**
## What, How & Why?

This closes # ??? 

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [ ] 🚦 Tests
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary
* [ ] 🔔 Mention `@realm/devdocs` if documentation changes are needed

### CODE REVIEW

**Comment by kraenhansen** [comment]
Thanks for your PR. To ensure this problem doesn't regress, I'd be very interested in getting a better understanding and an actual test reproducing it.

**Comment by kraenhansen** [comment]
@Ashik55 please reopen if you want to address my comment above 👍

**Comment by Ashik55** [comment]
@kraenhansen I am using  expo & getting data via atlas device sync & presenting in a calendar view by booking_date. as we have web application as well so when we are updating any booking's booking_date our expo mobile application crashes with with this exception.

So after adding this fix, application crash issue has resolved so if you feel it can help other you can merge the PR.
Thanks.

384634673-aace761c-d793-411b-9f18-d1f5fda2833a

**Comment by kraenhansen** [comment]
> if you feel it can help other you can merge the PR.

I would like to understand the problem better. I.e. under what circumstances does the error happen?
I mean, you're producing a fix to a problem that I can't reproduce.

**Pull request closed without merging**
