### PR TITLE
revert arguments when call callFunctionOnService to spread variable

### PR DESCRIPTION
**Pull request by deckyfx**
## What, How & Why?

in version 12+, the User function called from the client always sends arguments wrapped in Array,
I compare the code with version 11+ and found out that function `callFunction` pass the `args` to next function `callFunctionOnService` as a single array argument instead of spread arguments

This should resolve [#6447 ](https://github.com/realm/realm-js/issues/6447)

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [ ] 🚦 Tests
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

**Review by kraenhansen — APPROVED** [review]
Thanks for catching this and providing a PR, ideally, I would love if we could also add a test to ensure this doesn't regress.

**Comment by kraenhansen** [comment]
We do seem to have tests for this, so I'll have to look into why they're not failing https://github.com/realm/realm-js/blob/main/integration-tests/tests/src/tests/sync/user.ts#L636-L672

**Comment by kraenhansen** [comment]
Unfortunately, I wasn't able to pick your change into my branch, but I updated the test and implementation in https://github.com/realm/realm-js/pull/6451 and as such I'll close this PR.

You'll be rightfully attributed in the changelog and release notes. Thanks again!

**Comment by deckyfx** [comment]
np, as long as this issue is resolved, thanks for your attention <3

**Pull request closed without merging**
