### PR TITLE
Updating to core 4.0.0 and sync 2.0.0-rc25

### PR DESCRIPTION
**Pull request by kneth**
An update to latest and greatest.

### CODE REVIEW

**Comment by bmunkholm** [comment]
👍  when CI passes.

**Comment by bdash** [comment]
It looks like sync_config.cpp needs to be added to the Xcode project and react-native/android/src/main/jni/Android.mk as well.

**Comment by bdash** [comment]
The CI failure looks to be because `sync_config.cpp` was added to the wrong target of the Xcode project (GCDWebServers rather than RealmJS). I'm happy to push a fix for this if you'd like.

**Comment by blagoev** [comment]
👍

**Comment by kneth** [comment]
Yes, it's the usual simulator issue.

**Pull request merged**
