### PR TITLE
`realm-web` BaaS QA test server

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

- Updates the `realm-web` integration tests to run against the shared QA test cluster, instead of spinning up it's own baas test server using docker. This aligns the way we run tests for our main integration tests of the root package.

### CODE REVIEW

**Comment by kraenhansen** [comment]
I moved the stuff needed to fix `realm-web` on `andrew/app-importer/rules` to a separate PR: https://github.com/realm/realm-js/pull/5483

**Comment by kraenhansen** [comment]
This PR currently fails because we need to add replacements to change the service type from "mongodb" to "mongodb-atlas" when running against the QA server as we do it for the integration tests: https://github.com/realm/realm-js/blob/master/integration-tests/tests/src/utils/import-app.ts#L77

**Review by takameyer — APPROVED** [review]
I would say that's a big improvement!  LGTM

**Comment by kraenhansen** [comment]
This needs an update or a close now that we've started testing against BaaS in docker.

**Comment by kraenhansen** [comment]
Closing as it got superseded by #6368

**Pull request closed without merging**
