### PR TITLE
Upgrading to Realm Sync 3.5.8

### PR DESCRIPTION
**Pull request by kneth**

### CODE REVIEW

**Comment by bmunkholm** [comment]
@kneth Are there any fixes from the new sync version?

**Comment by kneth** [comment]
@bmunkholm Better write performance for large transactions.

**Comment by bmunkholm** [comment]
Then that should be rolled up in the release notes.

**Comment by kneth** [comment]
@bmunkholm It has already been added to `CHANGELOG.md` when core was updated (`Improved performance for devices which can support large address spaces.`)

**Pull request merged**
