### PR TITLE
Add 'deleteRealmIfMigrationNeeded' to configuration to delete a Realm…

### PR DESCRIPTION
**Pull request by ashwinphatak**
… if migration needed (#502)

## What, How & Why?

Reference to the issue(s) addressed by this PR: #502 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [x] 🚦 Tests
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [x] typescript definitions file is updated
* [x] jsdoc files updated
* [x] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Comment by ashwinphatak** [comment]
I'll add a check for that. 

Might also make sense to add another check such that `readOnly` and `deleteRealmIfMigrationNeeded` are not set at the same time.

**Comment by ashwinphatak** [comment]
Better now?

**Comment by pmiri** [comment]
Can this include an update to the documentation? Thanks!

**Comment by kneth** [comment]
It is documented in https://realm.io/docs/javascript/latest/api/Realm.html#~Configuration. Of course, we could mention it in https://realm.io/docs/javascript/latest#opening-realms.

**Pull request merged**
