### PR TITLE
[WIP] collection change notifications

### LINKED ISSUE #296: Fine grained notifications

### PR DESCRIPTION
**Pull request by alazier**
Closes #296

### CODE REVIEW

**Comment by rturk** [comment]
Can't wait to test this!
```
this.todoLists.addListener((name, changes) => {
console.log("changed: " + JSON.stringify(changes));
});
```

**Comment by rturk** [comment]
Hi @	alazier any updates?

**Comment by alazier** [comment]
@rturk - this work is pretty much done but we have some other dependencies which need to be resolved before we can release it. I hope we can get this out later next week if everything goes as expected.

**Comment by audunf** [comment]
Hi @alazier - any updates on this?

**Comment by alazier** [comment]
@audunf this functionality should be released very soon

**Comment by alazier** [comment]
This has been pushed to master in another pr.

**Pull request closed without merging**
