### PR TITLE
Add clang-format commit to gitignore-revs

### PR DESCRIPTION
**Pull request by tomduncalf**
## What, How & Why?

This closes # ???

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Comment by blagoev** [comment]
Should this `git config blame.ignoreRevsFile` be mentioned somewhere in the contributing docs, cause it is something everyone will need to do locally it seems.

**Comment by tomduncalf** [comment]
> Should this `git config blame.ignoreRevsFile` be mentioned somewhere in the contributing docs, cause it is something everyone will need to do locally it seems.

Ah I didn't realise it needed a git config change – in that case absolutely, I'll add something to `building.md`!

**Review by kraenhansen — APPROVED** [review]

**Comment by tomduncalf** [comment]
@blagoev added https://github.com/realm/realm-js/pull/4100/commits/ccf6e26a94123cf3e514e83d94bdd1013fd35811

**Review by kraenhansen — APPROVED** [review]

**Comment by tomduncalf** [comment]
Merging with unrelated simulator failure

**Pull request merged**
