### PR TITLE
Check peerDependencies in analytics post-install script

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

It looks our builder analytics is overestimating node.js usage. 

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [ ] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Review by tomduncalf — APPROVED** [review]
Seems like a reasonable change code-wise, I don't know about how it might or might not solve any overestimating

**Comment by kraenhansen** [comment]
What is the problem being solved here?

**Comment by kneth** [comment]
@kraenhansen Mostly defensiveness as we have seen an uptake of node.js which we cannot explain easily - only if Electron or React Native are not in `dependencies` or `devDependencies`.

**Comment by kraenhansen** [comment]
Some package need to declare react-native or electron as dependency, perhaps resolving it using `require.resolve("react-native/package.json")` would be more robust?

> which we cannot explain easily

I would assume some assumption of the script is wrong all-together. I'd suggest investigating the root cause of the uptake as an alternative to merging this PR. I fear this change would be causing more confusion than solving any issue.

For one, we should probably test the script with all known package managers being used out there (including but possibly not limited to yarn and pnpm).

**Comment by kneth** [comment]
I am closing this PR as we believe it requires more investigation: https://github.com/realm/realm-js/issues/4998

**Pull request closed without merging**
