### PR TITLE
Frozen results during iteration.

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This change will align the iterator behaviour with Realm Cocoa.

Reference to the issue(s) addressed by this PR: #1366

## ☑️ ToDos

* [x] 📝 Changelog entry
* [x] 🚦 Tests
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] ~~typescript definitions file is updated~~
* [x] jsdoc files updated
* [ ] ~~Chrome debug API is updated if API is available on React Native~~

### CODE REVIEW

**Comment by bigfish24** [comment]
We need some doc updates to emphasize when this won’t help you.

**Comment by blagoev** [comment]
@bigfish24 @fealebenpae @kneth what do you think on my last comment. (pinging here to accelerate the PR)

**Comment by bigfish24** [comment]
Yes to adding to other methods as well. Sorry I couldn’t tell from Yavor’s comment if we could add to others too.

**Comment by fealebenpae** [comment]
@blagoev the iterated collection is only going to change if you cause it to mutate in the body of the iteration as in the example in #1366. I think the collection methods are a lot less likely to do that as users don't normally mutate the objects in the collection in `map` or `find`. IMO we can just document this behavior for now - we implement `Symbol.iterator` ourselves so it was easy to fix the `for-of` iteration, but we directly copy a bunch of Array methods on our Collection prototype and making them use `snapshot()` would be more involved.

**Comment by blagoev** [comment]
indeed users will not modify the collection during these calls. at least it is not common. my vision is if these calls like find get messed up by a background sync for example

**Comment by blagoev** [comment]
we could merge this and then later revisit to broaden the fix

**Comment by fealebenpae** [comment]
Another thread writing to the realm file cannot cause this as the main thread will be too busy executing the iteration to run the event loop and advance to a newer read transaction. That leaves us with the user manually mutating the collection or manually advancing the realm transaction (in the case where there is another writer that will have mutated the collection).

**Comment by kneth** [comment]
As it is a breaking change, I would like to include it in 2.0.

**Comment by blagoev** [comment]
👍

**Comment by blagoev** [comment]
@fealebenpae still the forEach method is a candidate to be included. but lets leave it as it is for now

**Comment by kneth** [comment]
Merging - works on my machine.

**Pull request merged**
