### PR TITLE
handle error responses

### PR DESCRIPTION
**Pull request by ironage**
We should let object store handle the responses, there is logic there already to parse valid json and show the error. Intercepting these here means we would need special handling in the js onError code to parse the json or pass through the entire response like this: `"{"error":"cannot find app using Client App ID 'smurf'"}"`
TODO:
- [x] increment the version of realm-network-transport
- [x] publish this
- [x] upgrade js dependency on v10

### CODE REVIEW

**Comment by ironage** [comment]
@kneth if this makes sense, can you publish?

**Comment by kraenhansen** [comment]
I need to remember to update Realm Web after this change has been merged.

**Comment by kneth** [comment]
I think the consequence is that even when the callbacks from object store have no error defined, we might be in an error situation.

**Comment by ironage** [comment]
This change combined with https://github.com/realm/realm-js/pull/2901/commits/e7485f477b94c9038f3b4a617cf9dd5b797b2eef will handle both a network error from the transport as well as errors generated from valid json returned from the stitch server. If the object-store code fails to parse the response body, it will return "http error code considered fatal" just based on the response code.

**Comment by kneth** [comment]
@ironage In that case, I am all for it.

**Comment by ironage** [comment]
I don't have access to the npm user to publish this, can someone do it for me?

**Comment by ironage** [comment]
I've published realm-network-transport 0.3.0

**Pull request merged**
