### PR TITLE
Update the ReactTestApp

### PR DESCRIPTION
**Pull request by takameyer**
RN 0.66.3
Use our new metro.bundler.config to symbolically link realm and the tests

## ☑️ ToDos

* [x] 📝 Changelog entry

### CODE REVIEW

**Review by kraenhansen — APPROVED** [review]
Looks about right 🙂 

I suppose you also need to remove a couple of `install-local` invocations in the Jenkinsfile too:
- https://github.com/realm/realm-js/blob/andrew/rntestapp/scripts/test.sh#L300
- https://github.com/realm/realm-js/blob/andrew/rntestapp/scripts/test.sh#L321
- https://github.com/realm/realm-js/blob/andrew/rntestapp/scripts/test.sh#L345

**Comment by takameyer** [comment]
> Looks about right 🙂
> 
> I suppose you also need to remove a couple of `install-local` invocations in the Jenkinsfile too:
> 
> * https://github.com/realm/realm-js/blob/andrew/rntestapp/scripts/test.sh#L300
> * https://github.com/realm/realm-js/blob/andrew/rntestapp/scripts/test.sh#L321
> * https://github.com/realm/realm-js/blob/andrew/rntestapp/scripts/test.sh#L345

I just made a push for that 😄

**Comment by takameyer** [comment]
Looks like there is still some modifications needed in the test scripts.  I'll look into this next week

**Comment by takameyer** [comment]
The amount of effort to get this to work isn't worth it.  Release builds were not working using our metro-bundler

**Pull request closed without merging**
