### PR TITLE
fix node-pre-gyp not found

### PR DESCRIPTION
**Pull request by blagoev**
This is a naive fix for node-pre-gyp not found thrown when installing realm. 
The reason for the error is unknown since node-pre-gyp is a dependency of realm-js.
 This is a PR just to get opinions and get the conversation started about this. 

I think right now it reproduces very easily on blank RN project with
react-native init testPreGyp
npm install realm -- fails to find node-pre-gyp

### CODE REVIEW

**Comment by fealebenpae** [comment]
When you reproduce this, does `node-pre-gyp` not install at all?

**Comment by kneth** [comment]
`node_gyp_pre` is a dependency so doesn't `npm install` install it?

**Comment by blagoev** [comment]
yes it is a dependency and still it's not found. strange right?
the steps to reproduce it are as simple as in the description

@fealebenpae @kneth

**Comment by kneth** [comment]
I have tried the following:

```
$ npm uninstall node-pre-gyp
$ react-native init mytest
$ cd mytest
$ npm install realm@rc

> realm@1.12.0 install /Users/kneth/tmp/mytest/node_modules/realm
> node-pre-gyp install --fallback-to-build

[realm] Success: "/Users/kneth/tmp/mytest/node_modules/realm/compiled/node-v48_darwin_x64/realm.node" is installed via remote
```

I see that `node-pre-gyp` is installed.

**Comment by blagoev** [comment]
I am trying 
`npm install realm`
also maybe in don't have `node-pre-gyp` installed globally. It this is not reproducing on your machine can you check if you have this module globally somewhere. Also I am using nvm so this might be related

**Comment by kneth** [comment]
I have tried to uninstall (`npm uninstall node-pre-gyp` and `npm uninstall -g node-pre-gyp`) and verified that I don't have `node-pre-gyp` in `$HOME/node_modules`.

```
14:47 $ npm install realm@rc

> realm@2.0.0-rc18 install /Users/kneth/node_modules/realm
> node-pre-gyp install --fallback-to-build

[realm] Success: "/Users/kneth/node_modules/realm/compiled/node-v48_darwin_x64/realm.node" is installed via remote
/Users/kneth
├─┬ bcrypt@1.0.3
│ └─┬ node-pre-gyp@0.6.36
│   ├─┬ nopt@4.0.1
│   │ ├── abbrev@1.1.1
│   │ └── osenv@0.1.4
│   ├─┬ npmlog@4.1.2
│   │ ├── console-control-strings@1.1.0
│   │ └─┬ gauge@2.7.4
│   │   ├── aproba@1.2.0
│   │   ├── signal-exit@3.0.2
│   │   └── wide-align@1.1.2
│   ├─┬ rc@1.2.1
│   │ ├── deep-extend@0.4.2
│   │ ├── minimist@1.2.0
│   │ └── strip-json-comments@2.0.1
│   ├─┬ request@2.83.0
│   │ ├── aws-sign2@0.7.0
│   │ ├── aws4@1.6.0
│   │ ├── caseless@0.12.0
│   │ ├── extend@3.0.1
│   │ ├── form-data@2.3.1
│   │ ├─┬ har-validator@5.0.3
│   │ │ ├─┬ ajv@5.2.3
│   │ │ │ ├── co@4.6.0
│   │ │ │ ├── fast-deep-equal@1.0.0
│   │ │ │ └── json-schema-traverse@0.3.1
│   │ │ └── har-schema@2.0.0
│   │ ├─┬ hawk@6.0.2
│   │ │ ├── boom@4.3.1
│   │ │ ├─┬ cryptiles@3.1.2
│   │ │ │ └── boom@5.2.0
│   │ │ ├── hoek@4.2.0
│   │ │ └── sntp@2.0.2
│   │ ├─┬ http-signature@1.2.0
│   │ │ └── assert-plus@1.0.0
│   │ ├─┬ mime-types@2.1.17
│   │ │ └── mime-db@1.30.0
│   │ ├── performance-now@2.1.0
│   │ ├── qs@6.5.1
│   │ ├── safe-buffer@5.1.1
│   │ ├── tough-cookie@2.3.3
│   │ ├── tunnel-agent@0.6.0
│   │ └── uuid@3.1.0
│   ├── rimraf@2.6.2
│   ├─┬ tar@2.2.1
│   │ ├── block-stream@0.0.9
│   │ └── fstream@1.0.11
│   └─┬ tar-pack@3.4.0
│     ├── fstream-ignore@1.0.5
│     └── uid-number@0.0.6
└─┬ realm@2.0.0-rc18
  └─┬ node-pre-gyp@0.6.38
    ├─┬ request@2.81.0
    │ ├── caseless@0.12.0
    │ ├─┬ har-validator@4.2.1
    │ │ ├── ajv@4.11.8
    │ │ └── har-schema@1.0.5
    │ ├── performance-now@0.2.0
    │ ├── qs@6.4.0
    │ └── tunnel-agent@0.6.0
    └── rimraf@2.6.2

npm WARN enoent ENOENT: no such file or directory, open '/Users/kneth/package.json'
npm WARN kneth No description
npm WARN kneth No repository field.
npm WARN kneth No README data
npm WARN kneth No license field.
```

**Comment by blagoev** [comment]
@kneth 
I am doing
`npm install realm`
not 
`npm install realm@rc`

I will try the `realm@rc` version. Also I am using nvm with node 7.1 which also can contribute to this.

Also others got this errors as well looking into our issues. 

I am not sure yet what may cause it but still this behaviour is recognized as realm-js failure not as npm failure, so I am for just workarounding it. Probably like the proposed change or something else.

**Comment by blagoev** [comment]
@fealebenpae I think it does not install at all

**Comment by blagoev** [comment]
ok it fails for `realm@rc` as well

**Comment by blagoev** [comment]
ok I think that when node-pre-gyp is installed as dependency on command
`npm install realm`
it does not put the node-pre-gyp script in `node_modules/.bin/node-pre-gyp` and it is not found. 

We need to either install node-pre-gyp again explicitly  as the suggested change or we can try to refer to it by full path

**Comment by blagoev** [comment]
closing this one for #1511

**Pull request closed without merging**
