### PR TITLE
Update to work with new object store object accessor API

### PR DESCRIPTION
**Pull request by tgoyne**
This does the bare minimum to get things to compile and pass tests with objectstore master. There's probably more that should be done, but I won't have time to do it.

### CODE REVIEW

**Comment by bdash** [comment]
The object accessor refactoring lays the groundwork for arrays of primitives. It's necessary for realm-js to update to the new API to pull in any new version of object store, including the soon-to-be-merged stable ID work.

**Comment by bdash** [comment]
This is ready to go once we have a core release that includes realm/realm-core#2624.

**Comment by bdash** [comment]
Core v2.8.1 includes realm/realm-core#2624. A Sync release that picks up that version of core should be available tomorrow.

**Comment by radu-tutueanu** [comment]
We need to update the node-server-sdk to work with the object accessor as well: https://github.com/realm/realm-js-private/pull/278

**Pull request merged**
