### PR TITLE
Add Podspec file to enable autolinking with cocoapods.

### LINKED ISSUE #884: Support React Native installed with CocoaPods
Goals: adding RealmReact 1.0.2 project into XCode with pod install of react-native@0.42.0.rc-3 will not result in compilation failure.

Expected results: success app build using RealmReact project with react-native@0.42.0.rc-3 inside XCode project.

Actual results: compilation failure on RealmReact.mm: 'React/RCTBridgeDelegate.h' file not found in RCTBridge.h.  This is most likely due to the iOS header breaking change introduced in react-native@0.40.0 where React Native headers are expected to be enclosed in angle brackets, e.g. <React/RCTBridge.h>.  Previously working on react-native@0.38.0 using same app code.

Steps to reproduce:
directory structure:  $root/app, $root/rn (app XCode project is sibling of react native directory rn)

1. npm install react@15.4.2 react-native@0.42.0.rc-3
2. npm install realm@1.0.2
3. include Yoga and React in Podfile:
target 'app' do

  use_frameworks!

  pod 'Fabric'
  pod 'Crashlytics'

  # React libraries
  pod 'Yoga', :path => '../rn/node_modules/react-native/ReactCommon/yoga', :inhibit_warnings => true
  pod 'React', :path => '../rn/node_modules/react-native', :subspecs => [
     'Core',
     'RCTActionSheet',
     'RCTAnimation',
     'RCTImage',
     'RCTLinkingIOS',
     'RCTText',
     'RCTNetwork',
     'RCTWebSocket',
  ], :inhibit_warnings => true

4. pod install to install Yoga and React Native
5. add RealmReact project into XCode from ../rn/node_modules/realm/react-native/ios/RealmReact.xcodeproj
6. compile iOS app

Version: Realm 1.0.2 / Xcode 8.1 / OS X El Capitan 10.11.6

### PR DESCRIPTION
**Pull request by sam-drew**
## What, How & Why?

Add a Podspec file, so that Realm can be installed using cocoapods, and autolinking can happen.

This closes #884  ???

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Comment by kneth** [comment]
@sam-drew Thank you for the contribution. Do we need to document how to use the podfile?

**Comment by mrbrentkelly** [comment]
Are you sure this actually fixes autolinking in React Native? Did you test it out? 

When I've tried to add a podspec for realm manually, autolink and run, the iOS build always fails...

The podspec in this PR references files from `"ios/**/*.{h,m}"` (which works for traditional React Native libraries with top level `ios/` and `android/` folders) but the react native bridging code for realm-js is located at `/react-native/ios` and has files with other extensions like `.mm`.  

The podspec also isn't including all the `.cpp` and `.hpp` files from the `src/` folder... Maybe that's ok but I would expect both RealmJS (engine) and RealmReactNative (bridging) to be autolinked?

**Comment by sam-drew** [comment]
Yep! It worked for me when testing/adding manually.
I do see what you mean however, and perhaps it needs further investigation.

**Comment by kmvkrish** [comment]
> Yep! It worked for me when testing/adding manually.
> I do see what you mean, however, and perhaps it needs further investigation.

I added the realm.podspec in the realm node module. Then linked the library with React Native 0.61. The realm got linked successfully. But I still face the error **"React/RCTBridge+Provate.h" file not found**. The error is also occurring when manually linking the RealmReact.xcodeproj in iOS.

Does Realm support React Native 0.60+?

**Comment by kneth** [comment]
> Does Realm support React Native 0.60+?

We are working the autolinking etc. for 0.60+ but haven't got all done.

**Comment by kneth** [comment]
@kraenhansen is testing/expanding it.

**Comment by ahood12** [comment]
@kraenhansen is there an ETA for the podspec files being added to the project? Is there any way I can help? This bug is currently blocking us from updating several of our applications to RN 0.61.2 and the latest version of realm. 

I have attempted to create pod spec files on my end but it has taken me awhile to wrap my head around how the project is organized and what the build process should look like.

**Comment by prscX** [comment]
Hi @kneth: Any update w.r.t RN61 > compatibility support? We really need this fix as not able to use Realm with RN61 > project.

Thanks
</ Pranav>

**Comment by kneth** [comment]
This PR has been replaced by #2586 which will be released soon.

**Pull request closed without merging**
