### PR TITLE
Adding support for arrayFilters in updates

### LINKED ISSUE #4247: Support for arrayFilters updates in the realm-web package
### Problem

As it current is, arrayFilters are not supported by the realm-web npm package. When passing an arrayFilters property in the third argument (`options`) as is expected when using the MongoDB Node.js driver, the following error message shows up.
```
No array filter found for identifier 'element' in path 'submissions.$[element].status'
```
The message hinted that the `arrayFilters` was not sent to the server. Looking at the POST request confirms that only the `upsert` option is passed to the serverless function on Realm. If the `arrayFilters` option is forced to the Realm function `updateOne`, the update works as expected. 

### Solution

PR to follow

### How important is this improvement for you?

_No response_

### PR DESCRIPTION
**Pull request by joellord**
## What, How & Why?
This PR is for the feature request [#4247](https://github.com/realm/realm-js/issues/4247).

This PR adds support for arrayFilters by passing the arrayFilters parameter to the Realm serverless function.

Additional testing was added to cover the case of an update with arrayFilters.

This closes #4247 

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Comment by kneth** [comment]
@joellord I have initiated CI on your PR, and I will report back the result.

**Comment by kneth** [comment]
We see a few linting errors:

Screenshot 2022-01-24 at 14 12 55

**Comment by joellord** [comment]
Fixed the linting errors.

**Comment by joellord** [comment]
I see that there is a test that fails, but I'm quite confused as to how to go to fix it. It seems like the test runner didn't have the credentials for docker.

**Comment by kraenhansen** [comment]
I did a new PR with your changes (to allow our integration tests to run) and got this result: https://github.com/realm/realm-js/runs/4950056552?check_suite_focus=true

```
1) App services
     Remote MongoDB
       can update documents using array filters:
   Error: Request failed (POST http://localhost:8080/api/client/v2.0/app/my-test-app-amkmy/functions/call): mongodb insert: "document" argument must be a object (status 400 Bad Request)
      at Function.fromRequestAndResponse (webpack-internal:///../realm-web/dist/bundle.dom.es.js:2868:24)
      at async Fetcher.fetch (webpack-internal:///../realm-web/dist/bundle.dom.es.js:3031:23)
      at async Fetcher.fetchJSON (webpack-internal:///../realm-web/dist/bundle.dom.es.js:3048:26)
      at async Context.eval (webpack-internal:///./src/remote-mongodb-service.test.ts:266:30)
```

**Comment by kraenhansen** [comment]
Now that https://github.com/realm/realm-js/pull/4265 is green, I believe its safe to merge.
Thanks a lot for the PR!

**Comment by jasontlouro** [comment]
Thank you @joellord! I just spent the morning working on array identifiers in MongoDB Realm only to realize that they don't work on `realm-web` (was running 1.4.0). Luckily found this and realized you built it into the latest version! You saved the day.

**Pull request merged**
