### PR TITLE
Remove unused JavaScriptModule

### LINKED ISSUE #1176: [RN 0.47.0]ReactPackage.java remove createJSModules function
Could I change [`RealmReactPackage.java`](https://github.com/realm/realm-js/blob/master/react-native/android/src/main/java/io/realm/react/RealmReactPackage.java#L18)
```
    @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```
to
```
    // @Override
    public List<Class<? extends JavaScriptModule>> createJSModules() {
        return Collections.emptyList();
    }
```
?

### PR DESCRIPTION
**Pull request by jaggs6**
## What, How & Why?

Fixes #1176 

## ☑️ ToDos

* [x] 🚦 Tests or is not necessary
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

**Comment by ovr** [comment]
Did you test your PR with RN `0.46` (posible you broke support for RN < 0.47)? Because you remove whole `createJSModules`

**Comment by ElvisChiang** [comment]
prefer https://github.com/crazycodeboy/react-native-splash-screen/pull/74/files

**Comment by kristiandupont** [comment]
Thank you for this PR, @jaggs6.
I think that the other two commenters have a point. Since this would make it not work with older versions, removing the `@override` annotation may be the better solution. Sorry about that.
Also, before we can accept your PR, would you kindly sign our [CLA](https://github.com/realm/realm-js/blob/master/CONTRIBUTING.md#cla)? Thank you.

**Comment by jaggs6** [comment]
No problem. Thanks guys.

_Sent from my OnePlus ONEPLUS A5000 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by jaggs6** [comment]
@kristiandupont @ElvisChiang @ovr thanks for the review. I have made the requested changes

**Comment by jaggs6** [comment]
@kristiandupont signed the CLA

**Comment by jaggs6** [comment]
@kneth can we please merge this

**Comment by jaggs6** [comment]
@ovr can we merge this please?

**Comment by jaggs6** [comment]
@kristiandupont thank you
@fealebenpae a new release maybe for this commit to fix the breaking change in RN 47. Thanks

**Comment by finian** [comment]
@kristiandupont May I ask when to ship this fix?  Badly needed for RN 47. Thanks.

**Comment by kristiandupont** [comment]
@finian we will make a new release this week.

**Comment by hunterway55** [comment]
Works for me, Thank-you.

**Pull request merged**
