### PR TITLE
Consolidate RealmNode.xcodeproj into RealmJS.xcodeproj

### PR DESCRIPTION
**Pull request by appden**
Moved it up one level since it references the whole source tree inside the src/ directory. Added the functionality to run Node tests from Xcode on the existing RealmNode target.

### CODE REVIEW

**Comment by alazier** [comment]
The react-native dir seems out of place now. Perhaps it should also be reorganized and moved under src? It is now the only src not under that directory.

**Comment by appden** [comment]
We need the React Native code to be in a separate Xcode project for compatibility with `rnpm`. Moving it under `src/` kind of implies that `RealmJS.xcodeproj` would access them, but it strictly does not. Also, the JS files need to stay there so `require('realm/react-native')` works.

**Comment by alazier** [comment]
Can the structure of our npm package can be different from the structure of our repo?

**Comment by appden** [comment]
Kind of, but requires writing some scripts and would complicate things.

**Comment by appden** [comment]
@alazier I would really like to merge this too

**Comment by alazier** [comment]
I'm not happy with this new structure. If this is needed for the other prs we can merge it and change it again later but as is this is kind of confusing.

**Pull request merged**
