### PR TITLE
Update realm.io/common to 0.1.2

### PR DESCRIPTION
**Pull request by tomduncalf**
## What, How & Why?

This fixes https://github.com/realm/realm-js/issues/4657.

I'm going to look separately if I can create a failing test for this cas.

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Review by takameyer — APPROVED** [review]
This seems to be a common problem when we update our internal packages.  We should set something up to catch this for us (or automate an update for dependent packages)

**Comment by kraenhansen** [comment]
I'd expect the package-lock.json to update from this change?

**Comment by tomduncalf** [comment]
Yep @takameyer, I'll create a ticket for that as it is very easy to miss (and quite hard to catch as our `package.json` specifies `^0.1.1` so in many cases will pull in the right version for a clean install regardless, but seemingly not for an upgrade install).

@kraenhansen Good point, I'll do an npm/lerna to update them

**Comment by tomduncalf** [comment]
Added package lock in https://github.com/realm/realm-js/pull/4660/commits/fb436c6f9c37764334ae32a8464d362b4c5db7bc

**Review by kraenhansen — APPROVED** [review]

**Pull request merged**
