### PR TITLE
Make Realm creation available extenally, update OS and Sync versions

### PR DESCRIPTION
**Pull request by alazier**
@kristiandupont @fealebenpae @gritzko @radu-tutueanu

### CODE REVIEW

**Comment by radu-tutueanu** [comment]
There are the breaking changes in realm-core 2.3.2 : https://github.com/realm/realm-core/commit/4322f25731a9eb44ae133b0a7a57bb547f83d377. ObjectStore unit tests do not compile `src/object_accessor.hpp` as far as I can tell.
You should update the core version in `dependencies.list` as well, used when building node without sync.

**Comment by radu-tutueanu** [comment]
Looks fine to me otherwise. Where would we use this function?

**Comment by alazier** [comment]
@radu-tutueanu this is used to create Realms in the correct execution context from within the global notifier/adapter.

**Comment by alazier** [comment]
Without this I don't think registering notifications on realms created from the notifier/adapter would work. Does this sound correct @fealebenpae ?

**Comment by radu-tutueanu** [comment]
👍 
@fealebenpae is on vacation until next week.

**Pull request merged**
