### PR TITLE
Remove the type for the `Object#_objectId`

### LINKED ISSUE #4820: Remove `Realm.Object#_objectId`
This is using the deprecated `GlobalKey` in core and [we've recently added another API](https://github.com/realm/realm-js/pull/4785) that can replace the need for this.

### PR DESCRIPTION
**Pull request by kraenhansen**
## What, How & Why?

This closes #4820

## ☑️ ToDos
* [ ] 📝 Changelog entry
* [ ] Migrate this over to the `_objectKey` introduced on master (after v11 has been rebased):
  * [ ] [tests/js/linkingobjects-tests.js#L219-L230](https://github.com/realm/realm-js/blob/kh/remove-objects-objectId/tests/js/linkingobjects-tests.js#L219-L230)
  * [ ] [integration-tests/tests/src/tests/class-models.ts#L114](https://github.com/realm/realm-js/blob/kh/remove-objects-objectId/integration-tests/tests/src/tests/class-models.ts#L114)
  * [ ] [lib/extensions.js#L78](https://github.com/realm/realm-js/blob/kh/remove-objects-objectId/lib/extensions.js#L78)
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* [x] 🚦 Tests
* [x] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [x] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [x] 📱 Check the React Native/other sample apps work if necessary
* [x] 📝 Public documentation PR created or is not necessary
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

**Comment by kneth** [comment]
I believe the JSON serializing will not work when `Realm.Object#_objectId` is removed (https://github.com/realm/realm-js/blob/master/lib/extensions.js#L78)

**Review by kneth — CHANGES_REQUESTED** [review]
I believe the JSON serializing will not work when Realm.Object#_objectId is removed (https://github.com/realm/realm-js/blob/master/lib/extensions.js#L78)

**Review by kneth — APPROVED** [review]

**Comment by kraenhansen** [comment]
LGTM. I would approve if this wasn't my own PR 🤦

**Comment by takameyer** [comment]
The tests seem to not be getting the `_objectKey` changes.  I'll have to look into this before merging

**Pull request merged**
