### PR TITLE
When refreshing the token, look up the user in a way that doesn't suffer from #1586

### PR DESCRIPTION
**Pull request by bdash**
Expose a means of looking up a user by identity and server to avoid problems if the same user identity exists for multiple servers, which can happen when connecting to the same server via different hostnames.

Works around #1586 in the token refresh subsystem.

This may fix https://github.com/realm/realm-object-server-private/issues/790.

## ☑️ ToDos

* [x] Should the new method be public? **No**
* [x] Should the new method be able to return a user that's logged out? **No**
* [x] 📝 Changelog entry
* [ ] 🚦 Tests
* [ ] ~📝 Public documentation PR created or is not necessary~
* [ ] ~💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* [ ] ~typescript definitions file is updated~
* [ ] ~jsdoc files updated~
* [ ] ~Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

**Comment by bdash** [comment]
@kneth, do you have any thoughts on the two questions asked in the ToDo list above?

**Comment by kneth** [comment]
@bdash I don't think it should be public. So far, we are the only one who has experienced it. And I doubt it is useful to obtain a logged-out user. So I say "no" to both questions.

**Comment by nirinchev** [comment]
@kneth what's the status of this? It appears to be the cause of somewhat frequent test failures in ROS and would be great if we could get it with the next js release.

**Comment by kneth** [comment]
@nirinchev Today is big merge day which means that it will be merge soon. I hope to do a release either later today or tomorrow.

**Comment by bdash** [comment]
Thanks for getting this merged, @kneth!

**Pull request merged**
