### PR TITLE
[v10] RN debugger fixes

### LINKED ISSUE #3358: Enabling React Native Debug mode causes Error: Must first create RPC session with a valid host from rpc.js:314
## Goals
Enable React Native **Debug** mode in order to troubleshoot console errors, set breakpoints, profile app, and monitor network requests.

## Expected Results
Mobile app connects to React Native Debugger successfully and I'm able to set breakpoints,  profile app, and monitor network requests, view console errors

## Actual Results
* Mobile App crashes with the following error

> Error: Must first create RPC session with a valid host from rpc.js:314

:19

Mobile App

### Sentry Stacktrace
```jsx
Error: Must first create RPC session with a valid host
  File "app:///rpc.js", col 18, in sendRequest
  File "app:///rpc.js", col 41, in setTimeout$argument_0
  File "app:///JSTimers.js", col 17, in _allocateCallback$argument_0
  File "app:///JSTimers.js", col 6, in _callTimer
  File "app:///JSTimers.js", col 6, in callTimers
  at <unknown>(app:///RNDebuggerWorker.js:2:134503)
```

## Steps to Reproduce

1. Run `yarn android` to build react native application and install on device
1. Shake device to reveal developer menu and select `Debug` . This is successful if the user is not logged in

   image

1. Login to account which causes realm database to be initialized
1. An exception occurs on mobile app

```
![https://user-images.githubusercontent.com/222459/96701643-bea69400-1388-11eb-911e-9ee8323b2795.png](https://user-images.githubusercontent.com/222459/96701643-bea69400-1388-11eb-911e-9ee8323b2795.png)
```

    The crash occurs when the following is called **`Realm.schemaVersion(Realm.defaultPath)`**     **`Realm.defaultPath`** displays an error when inspected using React Native debugger. See video below```
  image
```

## Code Sample
<!---
Please provide a code sample or test case that highlights the issue.
If relevant, include your model definitions.
For larger code samples, links to external gists/repositories are preferred.
Full projects that we can compile and run ourselves are ideal!
-->

```jsx
export const runMigration = ({currentSchema}: {currentSchema: any}) => {
  if (!schemas.length) {
    return {schemaVersion: 0};
  }

  **let nextSchemaIndex = Realm.schemaVersion(Realm.defaultPath);**
  schemas[schemas.length - 1].schema = currentSchema;

  // If -1, it means this is a new Realm file, so no migration is needed
  if (nextSchemaIndex !== -1) {
    while (nextSchemaIndex < schemas.length) {
      const migratedRealm = new Realm(schemas[nextSchemaIndex++]);
      migratedRealm.close();
    }
  }

  return {schemaVersion: schemas[schemas.length - 1].schemaVersion};
};
```

## Version of Realm and Tooling
* Realm JS SDK Version: 10.0.1
* Node or React Native: 0.63.3
* Client OS & Version: OnePlus 6 A6003, Android 10
* Which debugger for React Native: React Native Debugger

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes #3358 and #3361 

* Establish session between Chrome debugger and RPC server on device
* Create `Realm.App` instance on device and proxy object in Chrome debugger

## ☑️ ToDos

* [ ] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 🚦 Tests
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [ ] typescript definitions file is updated
* [ ] jsdoc files updated
* [ ] Chrome debug API is updated if API is available on React Native

### CODE REVIEW

**Comment by Anzormumladze** [comment]
we are waiting for your fixes as soon as possible

**Review by Muzzamil75 — COMMENTED** [review]
LEt it merge

**Comment by Anzormumladze** [comment]
> ## What, How & Why?
> This closes #3358 and #3361
> 
> * Establish session between Chrome debugger and RPC server on device
> * Create `Realm.App` instance on device and proxy object in Chrome debugger
> 
> ## ☑️ ToDos
> * [ ]  📝 Changelog entry
> * [ ]  📝 `Compatibility` label is updated or copied from previous entry
> * [ ]  🚦 Tests
> * [ ]  📝 Public documentation PR created or is not necessary
> * [ ]  💥 `Breaking` label has been applied or is not necessary
> 
> _If this PR adds or changes public API's:_
> 
> * [ ]  typescript definitions file is updated
> * [ ]  jsdoc files updated
> * [ ]  Chrome debug API is updated if API is available on React Native

can you tell how much time you need to finish this bug fix?

**Comment by kraenhansen** [comment]
Closing this in favour of https://github.com/realm/realm-js/pull/3411

**Pull request closed without merging**
