### PR TITLE
OpenSSL isn't linked due to typing error

### LINKED ISSUE #1864: SSL related issue when running on Linux + Electron
## Actual Results

I see this in the main process when running Studio 2.2.0:

```
/tmp/.mount_instal7w6CmU/app/realm-stu: symbol lookup error: /tmp/.org.chromium.Chromium.t4Fezq: undefined symbol: SSL_get0_param
```

## Steps to Reproduce

- Start an Ubuntu 16.04 box
- Download Studio 2.2.0 from https://studio-releases.realm.io/v2.2.0/download/linux-appimage
- Change permissions to allow the AppImage to be executed
- Execute Studio it from a terminal
- Connect to a server Realm to observe the error in the terminal from which Studio was launched

## Code Sample

N/A

## Version of Realm and Tooling

- Realm JS SDK Version: 2.6.0
- Node or React Native: Electron
- Client OS & Version: Ubuntu 16.04
- Which debugger for React Native: N/A

### PR DESCRIPTION
**Pull request by kneth**
## What, How & Why?

This closes #1864 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [x] 📝 `Compatibility` label is updated or copied from previous entry
* ~[ ] 🚦 Tests~
* ~[ ] 📝 Public documentation PR created or is not necessary~
* ~[ ] 💥 `Breaking` label has been applied or is not necessary~

*If this PR adds or changes public API's:*
* ~[ ] typescript definitions file is updated~
* ~[ ] jsdoc files updated~
* ~[ ] Chrome debug API is updated if API is available on React Native~

### CODE REVIEW

**Comment by kraenhansen** [comment]
Could we introduce a test that will prevent this regression from happening again (again)? :)

**Comment by kneth** [comment]
We could inspect the generated binary and let CI fail if SSL is missing.

**Comment by kraenhansen** [comment]
@kneth it would be great if we could set up some sort of guard, as it has happened twice.

**Comment by kneth** [comment]
@kraenhansen We can reintroduce https://github.com/realm/realm-js-private/pull/402.

**Pull request merged**
