### PR TITLE
Fail on Sync use when Sync is not available

### PR DESCRIPTION
**Pull request by blagoev**

### CODE REVIEW

**Comment by kristiandupont** [comment]
I don't understand why this is necessary as we should not be callig the extensions more than once, but the fix is fine and I guess if this solves it we're good.

**Comment by blagoev** [comment]
This does not work on node v4. I will look into different approach for this one

**Comment by kristiandupont** [comment]
How does it fail?

**Comment by blagoev** [comment]
It fails with Proxy is not defined.

**Comment by kristiandupont** [comment]
This has been solved by unified packaging

**Pull request closed without merging**
