### PR TITLE
Add a sync log capability to the AppProvider

### LINKED ISSUE #5517: Add Sync Log Configuration to AppProvider
### Problem

It's currently not straightforward to setup the sync logger in `@realm/react`.

### Solution

The following API could make this easier:

```tsx
      <AppProvider id={appId} logLevel={'trace'} logger={(level, message) => console.log(`[${level}]: ${message}`)}>
```

By default no logs would be produced, and a default logger could be provided that simply logs the level and message.

### Alternatives

_No response_

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Atlas Device Sync

### PR DESCRIPTION
**Pull request by takameyer**
## What, How & Why?
Make it easier to output sync logs in a `@realm/react` application
* Add a log level and logger arguments to the AppProvider
* Update Readme and tsdoc

This closes #5517

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 📝 `Compatibility` label is updated or copied from previous entry
* [ ] 📝 Update `COMPATIBILITY.md`
* [ ] 🚦 Tests
* [ ] 🔀 Executed flexible sync tests locally if modifying flexible sync
* [ ] 📦 Updated internal package version in consuming `package.json`s (if updating internal packages)
* [ ] 📱 Check the React Native/other sample apps work if necessary
* [ ] 📝 Public documentation PR created or is not necessary
* [ ] 💥 `Breaking` label has been applied or is not necessary

*If this PR adds or changes public API's:*
* [x] typescript definitions file is updated
* [ ] jsdoc files updated

### CODE REVIEW

**Comment by kraenhansen** [comment]
Could this easily base against `bindgen` instead?

**Comment by takameyer** [comment]
@kraenhansen It's possible, but I would have to [shave another yak](https://github.com/realm/realm-js/issues/5490)

**Comment by kraenhansen** [comment]
Yeah 🤔 it has to happen at some point though.

**Comment by takameyer** [comment]
@kraenhansen It's not only that.  The typings in `bindgen` has improved drastically, but also changed.  It's possible we will have to make v12 a peer dependency for the next versions of `@realm/react`.  Which could be fine, it will just be some time before we can make a release.

**Review by kneth — APPROVED** [review]
This is a good addition to `@realm/react`. We might be able to generalise it once the new core logging mechanism is released.

**Pull request merged**
