### PR TITLE
Windows ccache

### PR DESCRIPTION
**Pull request by iamer**

### CODE REVIEW

**Comment by takameyer** [comment]
The `ia32` architecture didn't store any ccache:
https://github.com/realm/realm-js/actions/runs/3582387632/jobs/6028137003

However, 64-bit looks to be successful.

**Comment by iamer** [comment]
> The `ia32` architecture didn't store any ccache: https://github.com/realm/realm-js/actions/runs/3582387632/jobs/6028137003
> 
> However, 64-bit looks to be successful.

Good catch, we will look into it

**Review by kneth — APPROVED** [review]
LGTM. Waiting for @takameyer's comment to be resolved.

**Comment by takameyer** [comment]
Merging now for the 64-bit ccache.  32-bit will be worked on in a separate PR.

**Pull request merged**
