### PR TITLE
Fix Android compilation (Using  EPOLL commit helper)

### PR DESCRIPTION
**Pull request by nhachicha**

### CODE REVIEW

**Comment by nhachicha** [comment]
@kristiandupont @alazier Android tests are passing `react-tests-android`

**Comment by alazier** [comment]
So on the last run the tests passed but the job kept running - so might be an issue detecting that everything finished running?
```
[macos_react_tests_release] [39;1mEncryptionTests[0m
[macos_react_tests_release]     [32;1m.[0m testEncryptedInvalidKeys ([33m0.082[0m seconds)
[macos_react_tests_release]     [32;1m.[0m testEncryptionValidKey ([33m0.100[0m seconds)
[macos_react_tests_release] 
[macos_react_tests_release] 
[macos_react_tests_release] [32;1m	 Executed 85 tests, with 0 failures (0 unexpected) in 6.897 (6.967) seconds
[macos_react_tests_release] [0m
[Pipeline] [macos_react_tests_release] step
[macos_react_tests_release] [Set GitHub commit status (universal)] SUCCESS on repos [GHRepository@547a1ae8[description= Realm is a mobile database: an alternative to SQLite & key-value stores,homepage=https://realm.io,name=realm-js,license=<null>,fork=false,size=87811,milestones={},language=C++,commits={},source=<null>,parent=<null>,url=https://api.github.com/repos/realm/realm-js,id=40667593]] (sha:aadb2f8) with context:react-tests Release
[macos_react_tests_release] Setting commit status on GitHub for https://github.com/realm/realm-js/commit/aadb2f8d3eccffdc7d93c6e6790bb2cfcfbe7cc5
[Pipeline] [macos_react_tests_release] }
[Pipeline] [macos_react_tests_release] // node
[Pipeline] [macos_react_tests_release] }
[android_react_tests] Waiting for tests.
[android_react_tests] Waiting for tests.
[android_react_tests] Waiting for tests.
[android_react_tests] Waiting for tests.
[android_react_tests] Waiting for tests.
```

**Comment by nhachicha** [comment]
@alazier I think the problem is that the first successful build run on a `Nexus 5X - 6.0` according to the [log](https://ci.realm.io/job/realm/job/realm-js/job/PR-707/1/consoleFull). The [second build](https://ci.realm.io/job/realm/job/realm-js/job/PR-707/2/consoleFull) failing, run on an unknown device to me 
```
Skipping device '0421416015082005fcc0' for 'app:debug': Could not find build of variant which supports density 320 and an ABI in armeabi-v7a, armeabi
1229 	:app:installDebug FAILED
```
cc @alebsack

**Comment by alebsack** [comment]
The first job ran on docker-cph-01 (success).  The second one on docker-cph-02 (failure).  Maybe they are slightly different?  cc @emanuelez

**Comment by emanuelez** [comment]
Only the device AFAIK

**Comment by alebsack** [comment]
@emanuelez To clarify, what model are the devices on each?

**Comment by emanuelez** [comment]
docker-cph-01: Nexus 5X
docker-cph-02: Nvidia Shield

**Comment by nhachicha** [comment]
we moved from FastLinux because it uses the`Nvidia Shield` & somehow the tests do no run on this device properly. 
Is it possible to configure the Jenkins to require Android tests to run on the Nexus 5 only?

**Comment by emanuelez** [comment]
Shouldn't it be figured out why some tests fail of such device instead?

**Comment by nhachicha** [comment]
@emanuelez the tests do not fail, they don't run first place. 

we did spend some time investigating this with @alebsack the issue is that the Activity responsible for running the RN tests is not brought to the foreground. It's difficult to investigate this remotely you need access to the device to see what happen when the RN Packager starts the APK.

**Comment by emanuelez** [comment]
You can use `docker-cph-01` as a node name instead of `android` to force the execution to the particular slave

**Comment by alebsack** [comment]
I've added the labels `nexus-5x` and `nvidia-shield` to those respective slaces.  So you can now choose `docker && android && nexus-5x`

**Comment by nhachicha** [comment]
Android is using `nexus-5` for tests, ready to review again @kristiandupont @alazier @emanuelez

**Pull request merged**
