### PR TITLE
Add Subscription import to browser/index.js and register type converter

### PR DESCRIPTION
**Pull request by artutra**
Fix "subscription not defined", described here #1711 
### Testing
- Create a react native application
- Install `realm@2.3.3`
- Add a `import Realm from 'realm'` somewhere in the code
- Turn the debugger on

### CODE REVIEW

**Comment by artutra** [comment]
It solves the "subscription not defined" problem but it starts to show "logout already defined", that can be solved if I delete this line:
https://github.com/realm/realm-js/blob/c3a83f1866542a148a52495a8e7f014c57c33c66/lib/browser/user.js#L45
Can someone tell me the importance of this definition? I find another definition for "logout" here in:
https://github.com/realm/realm-js/blob/c3a83f1866542a148a52495a8e7f014c57c33c66/lib/user-methods.js#L386

**Comment by ShadowManu** [comment]
Guys, I know I may be another bugging developer, but could you take a look at this PR?
I'm running from bugs in React Native's AsyncStorage and coming here for salvation :laughing:
This bugs block me from using Realm in our app (manually applying the proposed solution and removing 'logout' works (or looks like at least) for me.

**Comment by kneth** [comment]
@artutra Thanks for the contribution. Please sign our [Contributor License Agreement](https://github.com/realm/realm-js/blob/master/CONTRIBUTING.md#cla).

Besides that, it looks fine to me :smile:

**Comment by artutra** [comment]
Done! ;)

**Comment by kneth** [comment]
@artutra Thanks!

**Comment by tregismoreira** [comment]
Thanks for your contribution, guys.
Any plans on package update?
https://www.npmjs.com/package/realm

**Comment by kneth** [comment]
I have released 2.4.0.

**Pull request merged**
