### PR TITLE
Don’t invoke openAsync callback twice

### LINKED ISSUE #1140: openAsync fires twice with an unexpected error for newly created realms
```js

let Realm = require('realm')

let admin = Realm.Sync.User.adminUser('ewoJImlkZW50aXR5IjogIl9fYXV0aCIsCgkiYWNjZXNzIjogWyJ1cGxvYWQiLCAiZG93bmxvYWQiLCAibWFuYWdlIl0KfQo=:WYLWgyTzDVn2BS/5vilJ7sbCuHyJBbslIKFW7jpknc0iL6l/vRqtp2H+RIV9/bmy4vbQDEdUksFKUpXprvKDZICam/930LSdgMPgIMEszz7r8iho1SBjfjCaniZ6DyAD9HxKLHhiDNe6W5LvViY1bAsHuLdLRYYlQxcrgG7SRhYNEXjrKJPzY46WWCbNh7x45UbPycZVRpfHOzUUuGLYGOnRbL0tokJm64+CYk7+C6BlGR32x4BL4v5unbBGj7+CVWTennY4ZhHQo9k/EyPuWZUwTjU2k505ziGp0FtFgiqK+XRFNodGdMqu7m8oZDEVY33/v+9rh0B2E/OI4yDCRg==')
let realm = new Realm({
	sync: {
		user: admin,
		url: 'realm://localhost:9080/test'
	}
})
realm.close()

Realm.openAsync({
	sync: {
		user: admin,
		url: 'realm://localhost:9080/test'
	}
}, (error, realm) => {
	console.log(error)
	console.log(realm)
})
```

This outputs
```
{ message: 'Operation canceled', errorCode: 89 }
undefined

null
Realm {}
```
indicating that the callback fires twice. The `Operation canceled` error is coming internally from Realm and is very misleading.

### PR DESCRIPTION
**Pull request by nirinchev**
## What, How & Why?

This fixes #1140 

## ☑️ ToDos

* [x] 📝 Changelog entry
* [ ] 🚦 Tests
* [x] 💥 `Breaking` label has been applied or is not necessary

### CODE REVIEW

**Comment by nirinchev** [comment]
Good call - I totally missed that `open` is returning a promise!

**Comment by nirinchev** [comment]
@blagoev do you have any idea why the build fails? I'm quite unfamiliar with the build infrastructure for Realm js, but wouldn't expect this change to be causing what appears to be native crash.

**Comment by blagoev** [comment]
@nirinchev I restarted the build and will see how it progresses

**Comment by blagoev** [comment]
@nirinchev I restarted the build and will see how it progresses

**Comment by nirinchev** [comment]
@blagoev should I merge this? Looks like there are failing builds - I'm not sure if that's expected or my change broke something.

**Comment by blagoev** [comment]
Will merge it.It is not related to the failing build

**Pull request merged**
